FROM vmware/admiral-base

COPY target/lib target/admiral-host-*.jar $ADMIRAL_ROOT/
COPY images-bin/* $USER_RESOURCES
COPY entrypoint.sh /entrypoint.sh
COPY configuration-vic.properties $DIST_CONFIG_FILE_PATH

ENTRYPOINT ["/entrypoint.sh"]