FROM vmware/admiral-base

ENTRYPOINT ["/entrypoint.sh"]

COPY entrypoint.sh /entrypoint.sh
COPY configuration-vic.properties $DIST_CONFIG_FILE_PATH
COPY logging-vic.properties $LOG_CONFIG_FILE_PATH

RUN mkdir $ADMIRAL_ROOT/log

COPY images-bin/admiral_agent.* $USER_RESOURCES
COPY target/lib target/admiral-host-*.jar $ADMIRAL_ROOT/
