#
# Copyright (c) 2016-2018 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Apache License, Version 2.0 (the "License").
# You may not use this product except in compliance with the License.
#
# This product may include a number of subcomponents with separate copyright notices
# and license terms. Your use of these subcomponents is subject to the terms and
# conditions of the subcomponent's license, as noted in the LICENSE file.
#

FROM photon:2.0-20181211

RUN tdnf distro-sync --refresh -y && \ 
    tdnf install git wget tar gzip unzip -y && \
    tdnf clean all

RUN wget https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.6.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go

RUN mkdir -p /go/src && \
    cd /go/src && \
    wget https://github.com/golang/net/archive/release-branch.go1.6.zip && \
    mkdir -p golang.org/x/net && \
    unzip release-branch.go1.6.zip -d golang.org/x/net && \
    mv golang.org/x/net/net-release-branch.go1.6/context golang.org/x/net && \
    rm -rf golang.org/x/net/net-release-branch.go1.6 release-branch.go1.6.zip

COPY /go /go
COPY /github-checkout.sh /

RUN ./github-checkout.sh fsouza/go-dockerclient 4a2e5288244cd60febbfc7bdd07891eab9efa6c1 && \
    ./github-checkout.sh fgrehm/go-dockerpty 9932a06dbe657616cf819adea2468666316a9e55 && \
    ./github-checkout.sh docker/docker 90be7a591de1f30332827a003edc39065fb8e4a7 && \
    ./github-checkout.sh hashicorp/go-cleanhttp ad28ea4487f05916463e2423a55166280e8254b5 && \
    ./github-checkout.sh Sirupsen/logrus 08a8a7c27e3d058a8989316a850daad1c10bf4ab && \
    ./github-checkout.sh docker/go-units eb879ae3e2b84e2a142af415b679ddeda47ec71c && \
    ./github-checkout.sh docker/engine-api ebc51d1954fc8934307dd15841b8d64f7cd505df && \
    ./github-checkout.sh opencontainers/runc faa3281ce8f09a1712898d6603e0746e63c6e2f0

RUN go install shellserver
RUN go install dockershell
