#
# Copyright (c) 2016-2018 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Apache License, Version 2.0 (the "License").
# You may not use this product except in compliance with the License.
#
# This product may include a number of subcomponents with separate copyright notices
# and license terms. Your use of these subcomponents is subject to the terms and
# conditions of the subcomponent's license, as noted in the LICENSE file.
#

# This docker image uses a custom .patch in order to compile shellinabox under # alpine linux. The original implementation can be seen here:
# https://github.com/gerco/shellinabox-alpine/blob/master/Dockerfile.build

FROM photon:2.0-20181211

RUN tdnf distro-sync --refresh -y && \
    tdnf erase toybox -y && \
    tdnf install git linux-devel-4.9.53-3.ph2 gcc glibc-devel openssl-devel zlib-devel autoconf automake make libtool tar binutils gawk sed diffutils file -y && \
    tdnf clean all

RUN ln -s /usr/src/linux-headers-4.9.53-3.ph2/arch/x86/include/uapi/asm /usr/include/asm
RUN ln -s /usr/src/linux-headers-4.9.53-3.ph2/include/uapi/asm-generic /usr/include/asm-generic
RUN ln -s /usr/src/linux-headers-4.9.53-3.ph2/include/uapi/linux /usr/include/linux

RUN git clone https://github.com/shellinabox/shellinabox.git \
    && cd shellinabox \
    && git checkout e6c25e84bc662797c7382500f136bb74874c2500

RUN cd shellinabox && \
    autoreconf -i && \
    ./configure && \
    make

RUN mkdir /shellinabox-bin && \
    mv /shellinabox/shellinaboxd /shellinabox-bin/

ENTRYPOINT /bin/sh
